version: '3'
services:
  webserver:
    image: node:16-alpine
    container_name: manga1
    # tty: true を設定することで止まらないようにする
    tty: true
    volumes:
      - ./myapp:/app
    ports:
      - '8080:3000'
    working_dir: /app
    command: >
      sh -c "echo === コマンド開始 === &&
      pwd && whoami && ls -la && 
      npm install && npm start"
